title: Mayaskar Chandrashekar
logo: /assets/img/Mayaskar_Photo.png
description: This is a sample project created for practising portfolio creation.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
